name: CI

on : 
    push : 
        branches : ["master"]

    workflow_dispatch: 


jobs : 
    build :
        runs-on : ubuntu-latest
        steps:
            - name : Hello-run
              run : echo Hello , World

            - name: Create the a file 
              run: |
                echo creating file 
                echo "hello from the cicd file" > demo.txt
                echo File created successfully!
            
            - name : Uploading the artifacts 
              uses: actions/upload-artifact@v7
              with :
                name: Demo artifacts
                path: .

            - name : End Process 
              run : echo Process Completed

    test :
        runs-on : ubuntu-latest
        needs: build
        steps:
            - name : Hello-run
              run : echo Hello , World           
            
